server:
  port: 8003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
  sql:
    init:
      mode: never

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7