server:
  port: 8002

spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://product-service-db:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
=======
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root
>>>>>>> 21ec763 (refactor(config): update service configuration for local dev environment)
  jpa:
    hibernate.ddl-auto: update
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://discovery-server:8761/eureka
=======
      defaultZone: http://localhost:8761/eureka
>>>>>>> 21ec763 (refactor(config): update service configuration for local dev environment)
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh