server:
  port: 8001

spring:
  mongodb:
<<<<<<< HEAD
    uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@user-service-db:27017/${MONGO_INITDB_DATABASE}?authSource=admin
=======
    uri: mongodb://root:root@localhost:27017/user_db?authSource=admin
>>>>>>> 21ec763 (refactor(config): update service configuration for local dev environment)

eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://discovery-server:8761/eureka
=======
      defaultZone: http://localhost:8761/eureka
>>>>>>> 21ec763 (refactor(config): update service configuration for local dev environment)
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh