server:
  port: 8001

spring:
  mongodb:
    uri: mongodb://root:root@localhost:27017/user_db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh